version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGO_URI=mongodb://mongo:27017/aicreative
      - N8N_URL=http://n8n:5678
      - N8N_USERNAME=${N8N_USERNAME:-admin@example.com}
      - N8N_PASSWORD=${N8N_PASSWORD:-admin123}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mongo
      - n8n

  frontend:
    build:
      context: .
      dockerfile: frontend/frontend.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=n8n
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - GENERIC_TIMEZONE=Asia/Shanghai
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USERNAME:-admin@example.com}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-admin123}
      - WEBHOOK_URL=http://localhost:5678/
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=regular
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      - NODE_ENV=production
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  mongo-data:
  n8n-data:
